### ISSUE TITLE
Yarn install throws 404

### ISSUE THREAD

**Issue by david-mears-dfe** [ministryofjustice/moj-frontend#106]
### Description

This is currently breaking our build:

`npm install --save @ministryofjustice/frontend` is successful

`yarn add @ministryofjustice/frontend` is unsuccessful with An unexpected error occurred: "https://registry.yarnpkg.com/@ministryofjustice%2ffrontend: Not found".

### Steps to Reproduce

1. Run `yarn add @ministryofjustice/frontend` from command line.

**Expected behaviour:** The package is installed.

**Actual behaviour:** A 404 error is thrown with An unexpected error occurred: "https://registry.yarnpkg.com/@ministryofjustice%2ffrontend: Not found".

**Reproduces how often:** All the time

### Versions

"0.0.19-alpha"

**Comment by david-mears-dfe** [comment]
This issue has stopped of its own accord

**Comment by likeuwill** [comment]
@david-mears-dfe because they npm fixed issue https://status.npmjs.org/ now servers status is green ;)

**Comment by johnnolan** [comment]
Closing this issue as it appears to have been an NPM service issue
