### ISSUE TITLE
Entry path for npm module is incorrect

### ISSUE THREAD

**Issue by solidgoldpig** [ministryofjustice/moj-frontend#109]
https://github.com/ministryofjustice/moj-frontend/blob/224840093df415cb9e80a5c84894feb086fd3f04/package/package.json#L5

The path should be `moj/all.js`

Any attempt to load the module via `require('@ministryofjustice/frontend')` currently results in the error:

```
Module not found: Error: Can't resolve '@ministryofjustice/frontend'
```

**Comment by johnnolan** [comment]
Fixed in the commit https://github.com/ministryofjustice/moj-frontend/commit/807c76f752c246c83263a891832361f1780f5853#diff-5205bfc4f58dc7ca1e3a58905757b4332c9e784666f28cadea2b4a1dd4b1e41d
