### ISSUE TITLE
Add unit tests to components using JavaScript

### ISSUE THREAD

**Issue by gregtyler** [ministryofjustice/moj-frontend#132]
## Summary

It would be helpful to add unit tests to this repo for all components which use JavaScript. These would be evaluated as part of the build process to ensure changes don't introduce regressions.

## Motivation

When making changes to components' JavaScript code it can be hard to know if you're introducing a regression. A test suite would provide a way of automatically detecting this as well as a written contract of what a component should do.

## Describe alternatives you've considered

I don't think there's really an alternative, but we should _also_ add visual regression tests (#133) to ensure the non-JavaScript components are degraded in future changes.

**Comment by robertjmccarthy** [comment]
Work underway and a number of tickets in backlog and assigned to cycles 4 and 5.
