### ISSUE TITLE
Add ticket panel examples to the frontend app

### ISSUE THREAD

**Issue by simonwhatley** [ministryofjustice/moj-frontend#135]
The `ticket-panel` component has been added to the [frontend package](https://www.npmjs.com/package/@ministryofjustice/frontend), but there aren't any examples in the [frontend app](https://moj-frontend.herokuapp.com/) or the MOJ Design System making it hard for users to discover and use the component.

**Comment by gregtyler** [comment]
There should be [examples](https://github.com/ministryofjustice/moj-frontend/blob/master/app/views/components/ticket-panel/index.html) in the frontend app, but the Heroku app isn't configured correctly so we can't deploy the latest version.

**Comment by gregtyler** [comment]
We've now successfully published the frontend app, and there's [a bug](https://github.com/ministryofjustice/moj-design-system/issues/60) tracking inclusion in the documentation
