### ISSUE TITLE
Pagination: configurable "results" label

### ISSUE THREAD

**Issue by markramsden-dwp** [ministryofjustice/moj-frontend#293]
It would be useful to be able to specify the text used to display the count of results so that instead of always saying (for example) "Showing 1 to 50 of 90 results" it could instead say "Showing 1 to 50 of 90 documents".

https://github.com/ministryofjustice/moj-frontend/blob/58420e658979e143468cd4e4315900db98c69bc5/src/moj/components/pagination/template.njk#L32

**Comment by gregtyler** [comment]
This sounds like a good idea and would be quite straightforward to add.

It's worth noting though that the pagination component is being [added to the GOV.UK Design System](https://github.com/alphagov/govuk-frontend/pull/2419) and they're researching the best way to allow customisation. For example, our component has hard-coded English in it so isn't possible to use with other languages.
