### ISSUE TITLE
Add modifier class to badge styles for text transformation

### ISSUE THREAD

**Issue by whatterz** [ministryofjustice/moj-frontend#36]
The default case for badges is uppercase. This may cause readability issues. Consider adding a set of modifier classes to allow the explicit setting of text transformation.

For example:
- `moj-badge--capitalize`
- `moj-badge--lowercase`
- `moj-badge--sentence` (where text transform would be `none`)

**Comment by whatterz** [comment]
@adamsilver @gavinwye thoughts on the naming of modifier classes:
- "capitalize" versus the British "capitalise" versus "titlecase" (`text-transform: capitalize;`)
- "sentence" versus "sentencecase" versus "none" (`text-transform: none;`)

**Comment by adamsilver** [comment]
Is there evidence that having both types is necessary? I'm worried that
this encourages inconsistency.

**Comment by whatterz** [comment]
I don't have access to research, but `text-transform: uppercase` versus `text-transform: none` is a question of readability.

We likely don't need to cater for all text transformations.

@EveBayram has expressed the need for at least the ability to maintain the inputted case. I'll ask for rationale.

**Comment by whatterz** [comment]
Not doing.
