### ISSUE TITLE
Add Ticket Panel to Pattern Library Components

### ISSUE THREAD

**Issue by johnnolan** [ministryofjustice/moj-frontend#368]
## Summary

The ticket-panel component is not visible on the Pattern LIbrary site, this will add it so people can view it.

## Motivation

I am getting requests of what it looks like and how it works. Pointing to this site takes away that problem.

## Describe alternatives you've considered

None

## Additional context

None

**Comment by robertjmccarthy** [comment]
[Ticket panel component](https://design-patterns.service.justice.gov.uk/components/ticket-panel/) is in the design system.
