### ISSUE TITLE
Archive Pagination component

### ISSUE THREAD

**Issue by gregtyler** [ministryofjustice/moj-frontend#440]
Now that the GOV.UK Design System has [a Pagination component](https://design-system.service.gov.uk/components/pagination/) we should archive ours and point new users towards the GDS one.

The GDS component was originally based on the MOJ component, with some further improvements from testing and feedback, which means:

- The GDS version has more user and accessibility testing and can therefore generally be presumed to be "better"
- They should be similar enough to make switching easy (for those that want to: we're archiving—not removing—the component!)
- We should be proud of our colleagues' work on this component, which they designed and built so well that the Design System team picked it up and it will now benefit departments across government 🎉

**Comment by robertjmccarthy** [comment]
Closing this ticket as pagination component added to roadmap. Mini discovery will take place to validate the assumption to remove and direct towards the GOV component.
