### ISSUE TITLE
Colour contrast for Primary navigation hover is not AA compliant

### ISSUE THREAD

**Issue by gregtyler** [ministryofjustice/moj-frontend#447]
### Description

When hovering over a navigation item on the [Primary navigation component](https://design-patterns.service.justice.gov.uk/components/primary-navigation/), the link text is `#5694ca` on a background of `#f3f2f1`. At a colour contrast ratio of 2.89:1, this is not AA accessible.

![image](https://user-images.githubusercontent.com/100852/224289722-c47d6432-5349-4dea-87ab-fc9f7108bd6b.png)

### Versions

Discovered in v1.6.4, but presumably has been a problem for much longer.

### Additional Information

The [GOV.UK Design System documentation](https://design-system.service.gov.uk/) (which I think the component was originally forked from) is now using a darker colour and additional underline on hover, which fixes the contrast issue and also ensures users who aren't able to detect the contrast difference can still see a hover effect.

![image](https://user-images.githubusercontent.com/100852/224289819-d54ed058-d82f-48da-ad50-97cd632d0c41.png)

**Comment by richpjames** [comment]
This is also an issue in [Subnavigation](https://design-patterns.service.justice.gov.uk/components/sub-navigation/)
