### ISSUE TITLE
Asset - Font folder missing

### ISSUE THREAD

**Issue by TejendraPrasad** [ministryofjustice/moj-frontend#568]
Hi Team,

I have installed package using NPM https://www.npmjs.com/package/@ministryofjustice/frontend

However, i cannot find  Font folder under - @ministryofjustice\frontend\moj\assets

ERROR in ./ClientContent/css/mojuk.scss (./ClientContent/css/mojuk.scss.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[0].use[2]!./ClientContent/css/mojuk.scss) 5:36-103
Module not found: Error: Can't resolve '/assets/fonts/light-94a07e06a1-v2.woff2'

**Comment by gregtyler** [comment]
That file is [distributed by govuk-frontend](https://github.com/alphagov/govuk-frontend/blob/main/dist/assets/fonts/light-94a07e06a1-v2.woff2), so I suspect you don't have govuk-frontend installed? If so you'll need to install it.

**Comment by TejendraPrasad** [comment]
@gregtyler, I had just took advice and added - 
$govuk-assets-path: "govuk-frontend/dist/govuk/assets/"; to add in MOJ..

I wanted to use Moj only navigation waiting govuk-frontend to have navigation..

This below code worked for me

$moj-assets-path: "@ministryofjustice/frontend/moj/assets/";

$govuk-assets-path: "govuk-frontend/dist/govuk/assets/";
@import "@ministryofjustice/frontend/moj/all.scss";
