### ISSUE TITLE
Notification banner component should allow autofocusing like the GOV.UK banner

### ISSUE THREAD

**Issue by chrispymm** [ministryofjustice/moj-frontend#619]
The GOV.UK notification banner allows for the role to be set to "alert" and has JS to autofocus the banner on page load in this case.

It would be helpful if our component had the same behaviour, as it is beneficial for accessibility.

**Comment by robertjmccarthy** [comment]
Closing this issue as recommendation from @chrispymm has been added to the [Banner component discussion](https://github.com/ministryofjustice/moj-frontend/discussions/835).
