### ISSUE TITLE
(Side nav 1) Build no-JS side navigation on staging site

### ISSUE THREAD

**Issue by robertjmccarthy** [ministryofjustice/moj-frontend#664]
## What
A side navigation for the MoJ Design System documentation site has been completed as a no-JS component. Some work has been done to progressively enhance the side nav (https://github.com/ministryofjustice/moj-frontend/pull/610). This task is to complete the work to include the progressive enhancement of open-and-close reveals.

## Why
To cater for a growing documentation site, and growing needs from the design system, a side navigation has been designed. This work is to be completed so that a Content Designer can add content to the no-js listing pages in preparation for going live with the new side nav setup on the documentation site.

## Who needs to be involved
- Developer

**Comment by chrispymm** [comment]
waiting on accessibility check from Ben

**Comment by chrispymm** [comment]
only one issue raised by accessibility review, and that has been fixed
