### ISSUE TITLE
Hold meeting on MoJ content style guide and make a Y/N decision

### ISSUE THREAD

**Issue by robertjmccarthy** [ministryofjustice/moj-frontend#666]
## What
Add a content style guide to the MoJ Design System guidance site.

## Why
HMPPS currently has a content style guide. To help bring more Content Designers to use the design system, and help the content design profession have a unified style guide, a version of the style guide is to go on the design system site.

## Who needs to be involved
- Content Designer

## Tasklist

- [x] Hold meeting on 1 Oct

**Comment by helennickols** [comment]
I'm moving this to done. There's a conversation upcoming with an engagement person about this being in the public domain, but otherwise it's been agreed upon.
