### ISSUE TITLE
Contact teams with date picker accessibility issues

### ISSUE THREAD

**Issue by robertjmccarthy** [ministryofjustice/moj-frontend#674]
## What
Check [accessibility audit report](https://docs.google.com/spreadsheets/d/1kDDGoBK0RvPvPPsffIvo1GuNJK8BkWxRPWiuOS3C4Qs/edit?usp=sharing) for any existing date picker component issues and reach out to teams to suggest using the released one.

## Why
The MoJ Design System has released a date picker component. Where teams are using an existing date picker on their product, and accessibility issues have been flagged, teams should adopt the date picker component from the design system.

## Who needs to be involved
- Design System Lead

**Comment by helennickols** [comment]
Feedback from @ushkarev today (in person): 
Adding the date picker to a form prevents the user from submitting it with a return button. They can submit if they tab through the date picker fields. CC @murrlipp @chrispymm 
This was demonstrated to me in the Incentives service.
