### ISSUE TITLE
Create a review process for GOV Frontend releases

### ISSUE THREAD

**Issue by robertjmccarthy** [ministryofjustice/moj-frontend#680]
## What
Create a review process for the MoJ Design System to undertake a review each time a new version of GOV Frontend is released.

## Why
Each time GOV Frontend undertakes a release, there may be updates that are needed to the MoJ Design System. For example, where a new component is released to the GOV.UK Design System, the GOV Figma Kit that the team support will need the component added to it.

## Who needs to be involved
- Design System Lead

**Comment by robertjmccarthy** [comment]
@murrlipp @chrispymm @helennickols 

I'm thinking we trial using Github issues to carry out reviews of GOV.UK Frontend releases rather than a document or miro board which we then would link to, but very open to changing that if this doesn't work.

The aim would be that we have a template setup for this task. When a new version of GOV.UK Frontend is released, we can create an issue from a 'release template'. On this proposed template, I've added some prompts to help us review releases from the GOV.UK Design System.

Could you have a look at [the proposed template](https://github.com/ministryofjustice/moj-frontend/issues/675) and see what you think please? It would be great to hear feedback on:

- Using github issues and comments to carry out the review.
- The prompts. Do these make sense? Are there any additional prompts we should consider?
- Anything else?

**Comment by helennickols** [comment]
@robertjmccarthy This looks good to me. I think I'll need to have a go at doing one to work out which would be the best questions.

**Comment by robertjmccarthy** [comment]
[Step-by-step process](https://dsdmoj.atlassian.net/l/cp/1RHao3cd) added to internal Confluence documentation.
