### ISSUE TITLE
Preparation for team away day

### ISSUE THREAD

**Issue by robertjmccarthy** [ministryofjustice/moj-frontend#682]
## What
The MoJ Design System team have an away day on 19 September 2024.

## Why
So that the team uses the time together effectively, this task is to track progress on preparing and planning for the day.

## Who needs to be involved
- Interaction Designer
- Content Designer
- Developer
- Delivery Manager
- Design System Lead

**Comment by helennickols** [comment]
hey @robertjmccarthy are we in 102PF for this? I've been looking into 10SC (Canary Wharf) for the content CoP away day and can share info if helpful.

**Comment by robertjmccarthy** [comment]
We are. We have the open collaboration space booked on 11th floor.

**Comment by robertjmccarthy** [comment]
Team captured photos of each of the sessions, which can be [seen here on a Miro board](https://miro.com/app/board/uXjVLeUhdRs=/?share_link_id=175209781330).
