### ISSUE TITLE
Discovery to improve page header actions component

### ISSUE THREAD

**Issue by robertjmccarthy** [ministryofjustice/moj-frontend#742]
## What
Run a discovery to improve the existing [page header actions component](https://design-patterns.service.justice.gov.uk/components/page-header-actions/) in the MoJ Design System.

## Why
As part of the improvement work being carried out on the [button menu component](https://design-patterns.service.justice.gov.uk/components/button-menu/), it has been found that there's a link between these two components. Work to improve the button menu component will continue, but it will be useful to run a discovery on the page header actions component to inform the improvement of the button menu.

## Who needs to be involved
- Interaction Designer
- Content Designer

## Tasklist

- [x] Ask content community about usage
- [x] Rework survey
- [x] Circulate survey
- [x] Set up 1:1 sessions
- [ ] Set disco deadline/end
- [ ] Write card to interpret findings and start next steps

**Comment by helennickols** [comment]
We can't set up 1:1 discussions until the survey responses has come in. @Whersi I suggest we move this into the next planning cycle and let the survey run next week during the planning week. CC @robertjmccarthy

**Comment by helennickols** [comment]
@murrlipp Could you find out the incidence of this through the Figma kit? So far, we know it's being used in sentence plan and in CSIP (not live).

**Comment by robertjmccarthy** [comment]
- [ ] #765 
- [ ] #779
