### ISSUE TITLE
Multiple MoJ Date Pickers - Incorrect Behaviour

### ISSUE THREAD

**Issue by iamfrankiemoran** [ministryofjustice/moj-frontend#751]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of the following:
  - Reproduced the problem
  - Followed all applicable steps in the debugging guide
  - Checked the FAQs on the message board for common solutions
  - Checked that your issue doesn't exist: https://github.com/ministryofjustice/moj-frontend/issues
  - Checked that there is not already a package that provides the described functionality

### Description
When using multiple MoJ Date Pickers on a single page, the Date Picker icon is duplicated for the first instance after rendering a second MoJ Date Picker.

### Steps to Reproduce

1. We have a dynamic page where components are hidden or shown depending on radio button or checkbox selection. 
2. Upon selecting a radio button or checkbox that displays an MoJ Date Picker, it renders correctly: 
![DatePicker](https://github.com/user-attachments/assets/1658966a-ee73-4b7b-a7e0-f1fb6b2f263a)
3. If we then select another radio button or checkbox that displays another MoJ Date Picker, the first MoJ Date Picker’s icon is duplicated: 
![DatePickerIconDuplicated](https://github.com/user-attachments/assets/cef8a206-3401-4894-b87f-8ad1dc4a6456)

**Expected behaviour:** 
Each MoJ Date Picker should render independently, and the first MoJ Date Picker should remain unaffected by the subsequent rendering of other MoJ Date Pickers.

**Actual behaviour:** 
The first MoJ Date Picker’s icon is duplicated when another MoJ Date Picker is rendered.

**Reproduces how often:** 
Occurs 100% of the time.

### Versions
@ministryofjustice/frontend": "^2.1.0"

### Additional Information
We suspect this issue may be due to targeting a class rather than an ID.

**Comment by chrispymm** [comment]
Thanks for reporting this.  Can I just clarify a few things to help isolate the issue:
* Are both date pickers in the markup initially? Or does the second datepicker get dynamically inserted into the DOM?
* Are you intialising the design system JS using `.initAll()` or via [initialising individual components](https://design-patterns.service.justice.gov.uk/get-started/setting-up-javascript#initialize-individual-components)?

If you're able to share your code or link to an example of the issue that would be helpful too.  Thanks.

**Comment by iamfrankiemoran** [comment]
@chrispymm thanks for getting back to me

So to answer your questions first:
1. Additional date pickers get added dynamically 
2. When they get called we call `.initAll()`

We're using it within an Angular application and have built a re-usable component which is linked here: [moj-date-component](https://github.com/hmcts/opal-frontend/tree/master/src/app/components/moj/moj-date-picker)

This is where we are using this component: [fines-mac-payment-terms-form](https://github.com/hmcts/opal-frontend/tree/PO-592/src/app/flows/fines/fines-mac/fines-mac-payment-terms/fines-mac-payment-terms-form)

Thanks in advance

**Comment by chrispymm** [comment]
Thanks for the quick response.  That's what I suspected - re-initializing the component is causing it to do the DOM manipulation twice resulting in multiple buttons.  

One solution you could implement now, would be, as you suggest, to add an `id` to the newly added picker and just initialise the new one using the [initialising individual components](https://design-patterns.service.justice.gov.uk/get-started/setting-up-javascript#initialize-individual-components) method.

```
const datePicker = document.querySelector('#datepicker2')
new window.MOJFrontend.DatePicker(datePicker,{}).init()
```

However, we should protect against double initialisation and make the component idemptoent, so I've got a working fix for this, and should hopefully be able to get it deployed soon.

**Comment by iamfrankiemoran** [comment]
I wanted to reach out to thank you for the swift resolution!

The latest MoJ library has been successfully merged into our master branch, and after testing, I can confirm the issue is fully resolved.

I really appreciate the quick turnaround on this – thanks again!
@chrispymm
