### ISSUE TITLE
Share discovery findings with team

### ISSUE THREAD

**Issue by Whersi** [ministryofjustice/moj-frontend#771]
## What
Add info about what the task is.

## Why
Add info about why this is a task to do.

## Who needs to be involved
- Interaction Designer
- Content Designer
- Developer
- Delivery Manager
- Design System Lead

## Tasks

- [ ] Add a task here

**Comment by robertjmccarthy** [comment]
@murrlipp and @helennickols have scheduled a discovery playback for 15 October 2025.

FYI @Whersi - The outcome of the session is to define the next stage of work to improve the page header actions.

**Comment by murrlipp** [comment]
@Whersi fyi this was completed so I'm moving it over.
