### ISSUE TITLE
Add formula/calculator for measuring time/waste saved to each component

### ISSUE THREAD

**Issue by Whersi** [ministryofjustice/moj-frontend#782]
## What
Add info about what the task is.

## Why
Add info about why this is a task to do.

## Who needs to be involved

- Delivery Manager
- Design System Lead

## Tasks

- [ ] Add a task here

**Comment by robertjmccarthy** [comment]
This task to be moved to cycle 4 as currently blocked pending a conversation with Performance Analysis Lead.

**Comment by robertjmccarthy** [comment]
Closing as we have a Performance Analyst now looking at how we can measure and define value from the design system.
