### ISSUE TITLE
Search in Slack for mentions of contributions

### ISSUE THREAD

**Issue by Whersi** [ministryofjustice/moj-frontend#793]
## What
Add info about what the task is.

## Why
Add info about why this is a task to do.

## Who needs to be involved
- Interaction Designer
- Content Designer
- Developer
- Delivery Manager
- Design System Lead

## Tasks

- [ ] Add a task here

**Comment by robertjmccarthy** [comment]
Closing this ticket as prioritisation has been carried out for components to be improved, and with a new squad coming in to do work on a component lifecycle model, adding components may not be a stream of work in the future.
