### ISSUE TITLE
Identity bar iteration

### ISSUE THREAD

**Issue by helennickols** [ministryofjustice/moj-frontend#803]
## What
@murrlipp identified that the button menu is being referenced and misnamed in [the Identity bar component](https://design-patterns.service.justice.gov.uk/components/identity-bar/#drop-down-action-menu). 
We think the work is:
- use the correct name for the Button menu in the Identity bar component
- deprecate the button row and link out to GOV.UK DS button group

## Why
Bring in line with button menu change. This is a small change. 

## Who needs to be involved
- Interaction Designer
- Content Designer
- FE dev

## Tasklist
- [x] Agree changes need to content
- [x] Agree changes needed to coded examples
- [x] Make content changes
- [x] Make changes to coded examples

**Comment by helennickols** [comment]
@Whersi @robertjmccarthy Adding this to the backlog. Not a high priority but also v small. If you already get notifications about new things being added let me know, as then I'll leave the issues in without tagging you.

**Comment by robertjmccarthy** [comment]
I don't get notifications when new issues are added in so the tag is appreciated. Although, I will look into whether I can get notifications for new issues as that'd be handy.

As this is linked to the button menu, and would be a shame to release an update and have this still live, I'll pull this into this cycle.

**Comment by helennickols** [comment]
@chrispymm Hey, I've done the [content](https://docs.google.com/document/d/1jcZIPj6xR0CQulhvHvCrWbd-DhiiSuMQQZKbxjHaqQM/edit) and added screenshots of the examples we agreed we would keep. 'To be' at the top, 'as is' at the bottom. Let me know if you have any questions!
