### ISSUE TITLE
Crest logo update

### ISSUE THREAD

**Issue by robertjmccarthy** [ministryofjustice/moj-frontend#829]
## What
Update any instances of the crest logo to a new crest logo. Communicate updates and release via MoJ Frontend, Figma, Slack and Notify.

## Why
As of 10 October 2024, a new Coat of Arms (crest) will be rolled out across Government.

## Who needs to be involved
- Interaction Designer
- Content Designer
- Developer
- Delivery Manager

## Done
This task is done when all instances listed below are updated to the new crest logo, and a release is communicated notifying users of the changes.

### MoJ Design System website
- [x] Logo in header
- [x] Crest in footer
- [x] Favicon

#### MoJ
- [x] https://www.figma.com/design/N2xqOFkyehXwcD9DxU1gEq/MoJ-Figma-Kit?node-id=20-17040
- [x] https://www.figma.com/design/N2xqOFkyehXwcD9DxU1gEq/MoJ-Figma-Kit?node-id=682-344
- [x] https://www.figma.com/design/x4AH3waUFmb6SW9iC38CJ0/New-and-improved-building-blocks?node-id=0-1
- [x] https://www.figma.com/design/CpTvAGL8rct5ugC8KWuXLz/Playground?node-id=20-17040

#### GOV.UK
- [x] https://www.figma.com/design/cdmqMa73kZBDEC42spSVba/GOV-Figma-Kit?node-id=2506-15992
- [x] https://www.figma.com/design/cdmqMa73kZBDEC42spSVba/GOV-Figma-Kit?node-id=384-103

### Components (MoJ Frontend)
- [x] https://design-patterns.service.justice.gov.uk/components/header/
- [x] EXAMPLE IMAGES: https://design-patterns.service.justice.gov.uk/components/button-menu/
- [x] EXAMPLE IMAGES: https://design-patterns.service.justice.gov.uk/components/date-picker/

### Patterns
- [x] SCREENSHOT: https://design-patterns.service.justice.gov.uk/patterns/add-to-a-list/

**Comment by murrlipp** [comment]
Changes made in branches on Figma and can be seen here:

##### GOV.UK

* https://www.figma.com/design/zKTfsDMO6zxrH10QMpWmwQ/Coat-of-Arms-update?node-id=2506-15992
* https://www.figma.com/design/zKTfsDMO6zxrH10QMpWmwQ/Coat-of-Arms-update?node-id=2852-6312&t=ChJhcmxU6ezs0mnU-4

**Comment by murrlipp** [comment]
Emailed Cabinet Office branding team today to query whether or not there is a simplified version of the coat of arms.  Moving into blocked while we await a response.

**Comment by Whersi** [comment]
The regular coat of arms logo was released and not the simplified version.
