### ISSUE TITLE
Slack comms for upcoming crest logo update

### ISSUE THREAD

**Issue by robertjmccarthy** [ministryofjustice/moj-frontend#830]
## What
Send comms out on Slack to communicate about the work the MoJ Design System team will be doing to update the crest logo to the header component in code and Figma. Include information about GDS not having a confirmed date for updating the footer but they will be communicating the release when they do. 

## Why
People may start to hear about the upcoming change and it would be good to inform people what we plan to do and manage expectations.

## Who needs to be involved
- Content Designer
- Design System Lead

## Done
When a Slack message is sent out.

**Comment by helennickols** [comment]
Warsome has written this. Looks great. have taken my name off as have given feedbacl. All good.
