### ISSUE TITLE
Review component discussion on Github

### ISSUE THREAD

**Issue by robertjmccarthy** [ministryofjustice/moj-frontend#838]
## What
Look through the [interruption card discussion on MoJ Frontend](https://github.com/ministryofjustice/moj-frontend/discussions/421) and on [GOV Frontend](https://github.com/alphagov/govuk-design-system-backlog/issues/27) to gather insights.

## Why
The purpose of this work is to gather information on who is using an interruption card in their product/service, how they are using it, and to see examples of it in use. Also, to gather names of people so that 1-2-1 discussions can be setup to understand more about the component.

## Who needs to be involved
- Interaction Designer
- Content Designer

## Done
When information is gathered from the discussion and added to a Miro board for synthesis.

**Comment by murrlipp** [comment]
@helennickols I've pulled all of the Github conversations onto the Miro and added some notes, but have left this ticket in 'In progress' because I feel there's a lot to be done in extracting any sort of actionable insight from the threads.
