### ISSUE TITLE
Update Nunjucks options for button menu and identity bar components

### ISSUE THREAD

**Issue by robertjmccarthy** [ministryofjustice/moj-frontend#847]
## What
Update Nunjucks for button menu and identity bar.

## Who needs to be involved
- Content Designer
- Developer

## Done
When the Nunjucks options are updated for the button menu component and the identity bar component, and committed to the `button-menu-updates` branch.

**Comment by helennickols** [comment]
I think this is from the href content. To discuss with C when he's back:

href | String | No | The URL that the button should link to. If this is set, element will be automatically set to a if it has not already been defined.
-- | -- | -- | --

**Comment by helennickols** [comment]
https://docs.google.com/document/d/1gUgZBtk6oejjyosor0yele9RI-E1oy8Yy0tlqsd1BKE/edit
Chris and I agreed this. Chris will make the changes now.

**Comment by helennickols** [comment]
Possible small change in https://mojdt.slack.com/archives/C06L8HYFJHM/p1729870193112269?thread_ts=1729865399.030229&cid=C06L8HYFJHM
