### ISSUE TITLE
RELEASE: Interruption card component

### ISSUE THREAD

**Issue by Whersi** [ministryofjustice/moj-frontend#854]
## Pre-release checklist

- [x] Content: prepared content for What’s new section of documentation website
- [x] Content: prepared Slack post
- [x] Content: prepared MoJ FE release note - M
- [x] Content: prepared Figma release note
- [x] Content: prepared Notify content
- [x] Team: agreed Slack post, Notify email and release notes
- [x] Lead: Create or update discussion on Github for released component

## Decision point
- [x] [Check the building block against the MoJ Design System standards](https://github.com/ministryofjustice/moj-frontend/issues/853)
- [x] Team decision point: is the release ready?

## Release checklist
- [x] Developer: Commit the changes to MoJ FE
- [x] Developer: Publish changes from staging to documentation site (inc. release notes)
- [x] Team: Check published version on a call (to start no later than 3pm on day of release)
- [x] Interaction: Merge component branch to main MoJ Figma Kit
- [x] Interaction: Publish update on Figma (inc. release notes)
- [x] Developer: Commit homepage content
- [x] Content: Send Slack post
- [x] Content: Send Notify email

## Post-release checklist

- [x] DM: Post the release notes in the Github discussion 
- [x] Lead: Add building block to analytics spreadsheet

**Comment by helennickols** [comment]
All done from me. I've left here for 2 bits for Rob.
