### ISSUE TITLE
(Side nav 5) Restructure site

### ISSUE THREAD

**Issue by robertjmccarthy** [ministryofjustice/moj-frontend#866]
## What
Add info about what the task is.

## Why
Add info about why this is a task to do.

## Who needs to be involved
- Interaction Designer
- Content Designer
- Developer
- Accessibility Specialist
- Delivery Manager
- Design System Lead

## Done
Add info about what this task looks like when it's done.

**Comment by helennickols** [comment]
@robertjmccarthy I'm working on the content items above.

**Comment by helennickols** [comment]
@robertjmccarthy [This doc](https://docs.google.com/document/d/1Nt60fYLt5PrveKGCzxb1vEcMuhSvH3UFW62sBiu4Yrg/edit?tab=t.0) might be helpful for the non-JS

**Comment by robertjmccarthy** [comment]
Redirects mapped out on a spreadsheet: https://docs.google.com/spreadsheets/d/1iMH24t-NEAEuvbr1O3PTU5_qfBzrwHOoIkiuSCR1wIo/edit?usp=sharing

**Comment by robertjmccarthy** [comment]
Site restructure completed and added to staging site. All changes added to the new-side-nav branch and included in [PR610](https://github.com/ministryofjustice/moj-frontend/pull/610).
