### ISSUE TITLE
(Side nav 8) Create content for no-JS pages

### ISSUE THREAD

**Issue by robertjmccarthy** [ministryofjustice/moj-frontend#869]
## What
Add info about what the task is.

## Why
Add info about why this is a task to do.

## Who needs to be involved
- Interaction Designer
- Content Designer
- Developer
- Accessibility Specialist
- Delivery Manager
- Design System Lead

## Done
Add info about what this task looks like when it's done.

**Comment by helennickols** [comment]
Content is in this doc - https://docs.google.com/document/d/1Nt60fYLt5PrveKGCzxb1vEcMuhSvH3UFW62sBiu4Yrg/edit?tab=t.0
