### ISSUE TITLE
(Side nav 9) QA and review

### ISSUE THREAD

**Issue by robertjmccarthy** [ministryofjustice/moj-frontend#870]
## What
Quality assure the restructured MoJ Design System website on staging: https://moj-frontend-staging.apps.live.cloud-platform.service.justice.gov.uk/

## Why
A number of pages have been moved and altered. It's useful to get a number of eyes looking at the work to check for broken links, typos, anything working in an unexpected way, etc.

## Who needs to be involved
- Interaction Designer
- Content Designer
- Developer
- User Researcher
- Delivery Manager
- Design System Lead

## Done
When everyone has completed a run-through of the website, noted down any feedback and observations, and the feedback is answered and resolved by the Design System Lead.

**Comment by KiahMadz** [comment]
Hi

Not sure I can add anything as detailed as Murray or that he hasn't already
picked up but things I noticed (and apologies if these are things you are
going to pick up at a later date/ are already aware of):


   - I clicked on all the links in the side nav and they all seem to be
   working and every page within each section is loading
   - On the filter a list page, the example seems to be misaligned

[image: Screenshot 2024-11-07 at 13.43.48.png]

   - Some of the embedded links within the main body of the pages don't
   work. I know you said redirects still need to be sorted out so maybe this
   will be picked up with that but some of them e.g. the 'question page' text
   link and the 'contact the design team' link on the add to a list page both
   go to 404 errors.

I think Murray has covered off everything else (and much more) that I
noticed.

Thanks,

Kiah

**Comment by helennickols** [comment]
QA feedback 

Tasks
- [ ] Broken link to contact the DS team - Murray is working on
- [ ] 404 link to Github from archived [Question pages component](https://moj-frontend-staging.apps.live.cloud-platform.service.justice.gov.uk/archive/question-pages/) - this is broken in live so might not be a priority (I have a merge conflict hence not just going in and fixing this) 
- [ ] Correct style to read Building blocks 
- [ ] Style guide in side nav to read Content style guide to match H1 (Murray also noticed so this is a duplicate)
- [ ] H1 to read 'Setting up JavaScript' 

I haven't added small errors which are in live as I don't want to proofread the whole site. 
I've also checked the no-JS pages. No issues.

**Comment by robertjmccarthy** [comment]
All feedback points completed apart from:

- [ ] I think the hover state of the active side nav item should have white text.
- [ ] Chevron directions don't change when expanding/collapsing sections.
- [ ] The change in background colour means the contrast of the border around examples is lower. It's now 1.94:1 instead of 2.08:1. [SC 1.4.11](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html) suggest 3:1 is needed if this is regarded a 'user interface component'.
- [ ] The same as above for contrast between page content and footer border.

@chrispymm and @murrlipp to look at these together and resolve.

Also, other comments were added for the content style guide. I'm going to move those over to a ticket in the content style guide epic so that doesn't hold up this side nav work.

**Comment by murrlipp** [comment]
On the last two points above, Ben has confirmed that the border colour contrast is not an accessibility issue, so these don't need to be addressed.
