### ISSUE TITLE
(Side nav 10) Add redirects

### ISSUE THREAD

**Issue by robertjmccarthy** [ministryofjustice/moj-frontend#871]
## What
Add info about what the task is.

## Why
Add info about why this is a task to do.

## Who needs to be involved
- Interaction Designer
- Content Designer
- Developer
- Accessibility Specialist
- Delivery Manager
- Design System Lead

## Done
Add info about what this task looks like when it's done.

**Comment by robertjmccarthy** [comment]
Redirects added to a spreadsheet ready for implementation: https://docs.google.com/spreadsheets/d/1iMH24t-NEAEuvbr1O3PTU5_qfBzrwHOoIkiuSCR1wIo/edit?usp=sharing

@chrispymm I'd suggest we implement 1 x redirect as a test before we go making massive structural changes to the site and then find out redirects aren't working.

**Comment by chrispymm** [comment]
@robertjmccarthy I've now implemented an initial redirect in staging now. If you visit:

https://moj-frontend-staging.apps.live.cloud-platform.service.justice.gov.uk/get-started/prototyping

you will be redirected here:

https://moj-frontend-staging.apps.live.cloud-platform.service.justice.gov.uk/prototyping/create-a-prototype/

This has been implemented using frontmatter in the markdown file of the new file, where you reference the old url. e.g.

```
---
redirect_from: /get-started/prototyping
---
```

If there are multiple pages you want to redirect from (i.e. multiple pages he been condensed into a new, different page) then you can use the format:

```
redirect_from: [/old-url/page, /some-other-page]
```

**Comment by robertjmccarthy** [comment]
Redirects are in place and on staging.
