### ISSUE TITLE
Service patterns prototype content review

### ISSUE THREAD

**Issue by robertjmccarthy** [ministryofjustice/moj-frontend#875]
## What
Martin (Lead Service Designer in Prisons Digital) has been working with DWP to trial the creation of service patterns. A prototype has been created and Martin has asked if (a) we can host the prototype as an orphaned page (or set of pages) on the design system website, and (b) as the prototype is content heavy, that the content is reviewed and improved by a Content Designer.

This work is timeboxed to 90 mins. The reason for timeboxing the work is that it could be a lot more involved, but as it's a prototype, and the design system team haven't been involved from the start of the work, we have to create a timebox instead of setting out the scope.

## Why
This work is to support colleagues working on service patterns that may have a place in the design system in the future.

## Who needs to be involved
- Content Designer

## Done
When the allocated time for the task is up, and the reviewed and improved prototype is sent to Martin.

**Comment by helennickols** [comment]
Moving to blocked as this is now with Martin FD ahead of our meeting tomorrow. It took 50 mins to review and re-write.

**Comment by helennickols** [comment]
I met Martin FD today to go through my content changes. We have a to-do list which we're going to check in with each other on on 15 November.

**Comment by helennickols** [comment]
@robertjmccarthy This is almost done. It needs some work from Murray to display the content. I was thinking of anchor links but that might not be the right option for this long page. Are you happy for Murray to do some work on this later in the week or shall we wait for Jan? Thanks

**Comment by helennickols** [comment]
@robertjmccarthy Hi Rob, I think your comment has been superseded and that we're all onboard for end of Dec. Is that right?

**Comment by robertjmccarthy** [comment]
@helennickols

I've done some work to finish off the Service Pattern prototype.

**What I've done**
- Added tabs to the 'apply' service pattern
- Resolved the push/check conflict on Github by using an active layout
- Updated a line on the service pattern page under 'Suggested MoJ service patterns' to link to the 'apply' pattern.
- Setup a folder for /service-patterns and changed the previous file to an index.md so the new (and any further) pages sit within this structure (e.g. /service-patterns/apply)

View the page on preview: https://moj-frontend-apply-service-pattern.apps.live.cloud-platform.service.justice.gov.uk/service-patterns/apply/

**Comment by robertjmccarthy** [comment]
PR reviewed and merged: https://github.com/ministryofjustice/moj-frontend/pull/1033

**Pages live**
- https://design-patterns.service.justice.gov.uk/service-patterns/
- https://design-patterns.service.justice.gov.uk/service-patterns/apply

**Comment by robertjmccarthy** [comment]
Work complete but moved to blocked so that @helennickols can have a look and decide if any further work is needed or to move to done.

**Comment by robertjmccarthy** [comment]
Moving to done as service pattern prototype now sent to Martin Ford-Downes.
