### ISSUE TITLE
No vertical spacing between buttons when viewing 290px (and below)

### ISSUE THREAD

**Issue by Whersi** [ministryofjustice/moj-frontend#878]
## What

No vertical spacing between buttons when viewing 290px (and below).

## Why

To ensure the component is visually appealing but more importantly user friendly

## Who needs to be involved
- Developer

## Done
When there is vertical spacing between buttons when viewing 290px (below).

**Comment by robertjmccarthy** [comment]
Fix applied to button menu component which the page header actions component uses.
