### ISSUE TITLE
New Cookie Banner design and Javascript module

### ISSUE THREAD

**Issue by johnnolan** [ministryofjustice/moj-frontend#92]
## Summary

Add a common component for the Cookie Consent Banner required by all public facing sites.

## Motivation

Every site being released at the moment has their own implementation. Ideally we need this to be done once in the design system and consumed by the front ends.

The Javascript is also potentially quite complicated due to multiple permissions. We should create a module for people to easily implement the functionality too.

## Describe alternatives you've considered

The alternative is to continue fragmenting the implementation across multiple projects.

There is also an existing implementation but it is deprecated and requires an enormous amount of JS to get working.

## Additional context

Ideally we want feedback from all departments in MoJ to make sure this component handles all functionality and design requirements for everyone.

**Comment by theDustRoom** [comment]
I've added this to the MOJ Frontend Backlog

**Comment by theDustRoom** [comment]
An example: https://components.publishing.service.gov.uk/component-guide/cookie_banner

**Comment by reyrrep** [comment]
Service: Send money to someone in prison.
Updated cookies in December 2019, making consent active.
URL: https://www.gov.uk/send-prisoner-money
![Pay_now_by_debit_card_–_Send_money_to_someone_in_prison_–_GOV_UK](https://user-images.githubusercontent.com/24682124/82307671-94574180-99b8-11ea-8e50-65c7ec2bde11.png)

![Cookies_–_Send_money_to_someone_in_prison_–_GOV_UK](https://user-images.githubusercontent.com/24682124/82307722-a638e480-99b8-11ea-9e28-cd0ad0d1c3b3.png)
