### ISSUE TITLE
User testing the documentation

### ISSUE THREAD

**Issue by robertjmccarthy** [ministryofjustice/moj-frontend#924]
## What
Test the Interruption Card documentation with a range of users (inc. Content Designers, Interaction Designers, and Developers).

## Why
To iterate and improve the documentation based on insights gathered through user research.

## Who needs to be involved
- Content Designer
- User Researcher

## Done
When testing has been completed and insights played back to the Content Designer.

**Comment by KiahMadz** [comment]
Draft of survey written here: https://docs.google.com/document/d/1kVZ57SJBGO_n80lrBfb8GzhnQm8lSr1YOHeZ40AtxTQ/edit?usp=sharing

Google form version of survey here: https://docs.google.com/forms/d/1aaIiJRlG8TygRU968C1AZ5uYPn91afLdTb8lGjMFx_A/edit

Have shared with Helen to do final review before sending out.

**Comment by helennickols** [comment]
@KiahMadz Bonjour, what do we think to the amount and quality of survey responses? There are some useful nuggets in there for me. It feels like closing it on Tues is still a good plan. Do you agree?

**Comment by helennickols** [comment]
@KiahMadz Reminder today sounds grand. Thank you!
