### ISSUE TITLE
Update how users can suggest a change and give feedback on a component

### ISSUE THREAD

**Issue by robertjmccarthy** [ministryofjustice/moj-frontend#937]
## What
Update the content on the [suggest a change page](https://design-patterns.service.justice.gov.uk/get-involved/suggest-a-change/) of the MoJ DS doc site so that it reflects the approach shown at the bottom of each of the component pages (e.g. [date picker](https://design-patterns.service.justice.gov.uk/components/date-picker/#:~:text=Get%20help%20and,date%20picker.) and [button menu](https://design-patterns.service.justice.gov.uk/components/button-menu/#:~:text=Get%20help%20and,on%20this%20component.))

## Why
The page directs users to a [Google form](https://forms.gle/FpDpbgttwmfmcz8o7) which populates a [backlog on a spreadsheet](https://docs.google.com/spreadsheets/d/1vcuScKiJW6Lbe8yGJphxE7Z6TO8Dt9phJxN9PPfM204/edit?usp=sharing). This is now a redundant process.

## Who needs to be involved
- Interaction Designer
- Content Designer

## Done
When the [suggest a change page](https://design-patterns.service.justice.gov.uk/get-involved/suggest-a-change/) is updated to reflect how users need to suggest changes on components.

**Comment by GrahamBaird1** [comment]
### Updated content

Get involved
**Suggest a change or give feedback**
To help improve the MoJ Design System, you can suggest changes to components and patterns.

The team wants to hear suggestions that may include:

- how you have used components and patterns in your service
- research or testing that can help improve an existing component or pattern
- reporting bugs where you've used a component or pattern in a live service and noticed an issue
- any feedback you have about usage, for example accessibility or ideas for improvements

Add these comments and take part in the [discussion on Github](https://github.com/ministryofjustice/moj-frontend/discussions/703).

**Screenshot**
![Image](https://github.com/user-attachments/assets/5b93206d-dabf-44f7-a42c-6635e988edc2)

---------------------------------------

### Previous content
Get involved

**Suggest a change or give feedback**
To help improve the MoJ Design System, you can suggest changes to components and patterns.

Useful suggestions may look like:

- new research or testing that can help improve an existing component or pattern
- reporting bugs where you've used a component or pattern in a live service and noticed an issue

**Tell us your suggestion**
Tell us about the change you're proposing by using the [suggest a change form](https://forms.gle/FpDpbgttwmfmcz8o7). The MoJ Design System Group will be notified of your suggestion and will review it.

Once reviewed, the group will either:
- accept your suggestion and work to apply your change
- accept your suggestion but work with you to tweak the changes before going ahead
- not accept your suggestion and explain why

**Get help**
You can [contact the MoJ Design System team for help or support](https://design-patterns.service.justice.gov.uk/help).

**Screenshot**
![Image](https://github.com/user-attachments/assets/5950b4a2-3495-49b8-be7d-c9c5425d2502)

**Comment by GrahamBaird1** [comment]
The content for this ticket is complete. 

The work is saved in this Google doc: [](https://docs.google.com/document/d/1ynz1M6eteBgtG-Abv66-26gFRu8Z3S8jUfmmQ8daXLw/edit?usp=sharing). 

The document includes the:
- original content raw text
- original content screenshot
- new content raw text
- new content screenshot

Tagging @murrlipp and @helennickols in this one as I believe it will be Murray who is updating it on the site. Also copying in @robertjmccarthy so you've got full sight of it. ✌️

**Comment by robertjmccarthy** [comment]
I can pick this one up today.

**Comment by robertjmccarthy** [comment]
@GrahamBaird1 I've added a comment to your GDoc. Could you review and let me know what you think please?

I've also committed the changes and it's awaiting a PR review: https://github.com/ministryofjustice/moj-frontend/pull/984

**Comment by robertjmccarthy** [comment]
All content changes made and pushed to live.
