### ISSUE TITLE
Write release notes

### ISSUE THREAD

**Issue by robertjmccarthy** [ministryofjustice/moj-frontend#942]
## What
Prepare release notes in advance of the Interruption card being released.

The release notes to be prepared are:

- [x] What’s new section of documentation website
- [x] MoJ slack  
- [x] XG slack
- [x] MoJ FE release note
- [x] Figma release note
- [x] Notify content

## Why
To communicate to users that the MoJ Design System has been updated and there is a new component available for reuse.

## Who needs to be involved
- Content Designer

## Done
When release notes have been created, reviewed, and approved, and are ready in a document for readiness on release day.

**Comment by helennickols** [comment]
These are in progress whilst I'm waiting for access to staging again:
https://docs.google.com/document/d/1rR75OfryYT5rqzuFruhUX74ebcly72If3oNRAgHSUNg/edit?tab=t.0

**Comment by helennickols** [comment]
Done and with the team
