### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by robertjmccarthy** [ministryofjustice/moj-frontend#943]
## What
Prepare release notes in advance of the Password reveal component being archived.

The release notes to be prepared are:

- [x] What’s new section of documentation website
- [ ] Figma release note
- [ ] Slack post
- [ ] Notify content

## Why
To communicate to users that the MoJ Design System has been updated and there has been a change they need to be aware of.

## Who needs to be involved
- Content Designer

## Done
When release notes have been created, reviewed, and approved, and are ready in a document for readiness on release day.

**Comment by helennickols** [comment]
Content is done on the component itself and so I'm moving on to this.

**Comment by helennickols** [comment]
@robertjmccarthy Do we need an MoJ FE release note too?
