### ISSUE TITLE
Build tabbed view of documentation page

### ISSUE THREAD

**Issue by robertjmccarthy** [ministryofjustice/moj-frontend#945]
## What
Build a tabbed template for displaying a building block and its documentation on the DS website. A design for the tabbed template has been created in Figma: https://www.figma.com/design/x4AH3waUFmb6SW9iC38CJ0/New-and-improved-building-blocks?m=auto&node-id=145-12555&t=Mqc4sKFkgWdw03Wm-1

## Why
Documentation for building blocks is very comprehensive. Displaying the content on a single page in a linear format means the page is very long. For a user this can be overwhelming when displayed in a linear format. We also know from research that users dip in and out of documentation. A linear format can make it difficult to scan and locate snippets of documentation that is relevant to their need.

## Who needs to be involved
- Developer

## Done
Using the Date picker component documentation as a sample, this task is complete when the tabbed view of the Date picker component documentation is available on staging.

**Comment by jbarnardmoj** [comment]
The design has the look of the sub navigation component for the menu but the functionality of the tab component. We need to clarify which component and functionality is required.

**Comment by jbarnardmoj** [comment]
I will move forward by enhancing https://design-patterns.service.justice.gov.uk/components/sub-navigation/ to toggle content visibility with a fallback to the existing anchor tag functionality if JavaScript is disabled.

**Comment by jbarnardmoj** [comment]
Approach was changed to: use the tab component and style it like the sub navigation component.

**Comment by jbarnardmoj** [comment]
Moving to blocked because there's some discussion about whether the accessibility review will change our implementation (we already had jquery tab functionality and are adding in the govuk tab component alongside that).

**Comment by jbarnardmoj** [comment]
Accessibility has been looked at now and this is back in review.
