### ISSUE TITLE
Update a few components to tabbed view

### ISSUE THREAD

**Issue by robertjmccarthy** [ministryofjustice/moj-frontend#946]
## What
Apply the tabbed documentation template to the Date picker, Button menu, and (if launched) Interruption card components.

## Why
The documentation for these components is comprehensive and are candidates for the tabbed documentation template.

## Who needs to be involved
- Content Designer

## Done
When the Date picker, Button menu, and (if launched) Interruption card components are using the tabbed template.

**Comment by helennickols** [comment]
I'm planning to come on to this on Monday morning.

**Comment by jbarnardmoj** [comment]
Usage:

Update the layout in the .md file:
layouts/tabbed-component.njk
Wrap the entire content in:
{% tabs "Contents" %}
{% endtabs %}
"Contents" is the name of the tabs but is not displayed

Then wrap each block of content that you want to be in a tab:
{% tab "Examples" %}
{% endtab %}
Where "Examples" is the label used in the tab
Finally add <hr /> below the tabs to separate from help content.

**Comment by murrlipp** [comment]
This is done and I have a draft PR in: https://github.com/ministryofjustice/moj-frontend/pull/1038

A bug in the tab shortcode is causing some items to be wrapped in `<p>` tags. Once @jbarnardmoj has merged a fix into`main` I can rebase this branch and request a review.

**Comment by jbarnardmoj** [comment]
The fix mentioned above is in PR #1039

**Comment by murrlipp** [comment]
https://github.com/ministryofjustice/moj-frontend/pull/1038 now includes the fix and is ready for review.
