### ISSUE TITLE
Community space and contribution form prototype

### ISSUE THREAD

**Issue by robertjmccarthy** [ministryofjustice/moj-frontend#948]
## What
Create a prototype that covers an early stage design for a community space of components and a contribution form to bring components to that space. The scope of this work is to be defined by the team as they progress the prototype, but the main aim is to have a prototype ready for testing in order for the team to assess the concept of a community space.

Also, work alongside the User Researcher to inform and support their preparation and planning for the first round of research and testing. For example, as the prototype develops, assumptions and questions for research and testing should be captured and shared with or by the User Researcher.

## Why
Testing a community space and contribution form prototype is to assess our initial confidence levels of the concept. If the concept of a community space is validated positively, further iteration and testing will aim to increase confidence levels.

## Who needs to be involved
- Interaction Designer (leading)
- Content Designer (leading)
- User Researcher (supporting)

## Done
This work is done when a prototype is prepared for the first round of testing w/c 9 December 2024.

**Comment by mattnixon1** [comment]
Prototype for round one of UR has been completed
