### ISSUE TITLE
Research preparation and planning

### ISSUE THREAD

**Issue by robertjmccarthy** [ministryofjustice/moj-frontend#949]
## What
Plan a round of moderated research and testing for a first prototype of a community space and contribution form. Work alongside the Interaction Designer and Content Designer whilst they develop a prototype to build out the preparations for the round of research and testing.

## Why
The concept of a community space needs to be assessed and the team's confidence levels need a benchmark. This round of research and testing is to assess whether there is confidence that a community space and contribution form could work to 'solve the problem of speed'.

## Who needs to be involved
- User Researcher (leading)
- Interaction Designer (supporting)
- Content Designer (supporting)

## Done
When preparation for a round of research is complete, including; discussion guide, recruitment of participants, and interviews scheduled for w/c 9 December 2024.

**Comment by KiahMadz** [comment]
Recruitment has started. 4 participants already booked in for weds 11th and thurs 12th december. Will review how many participants we have on monday and send out more recruitment invitations if no further responses. Also arranging access to consent kit so we can ask participants to confirm consent for recording the sessions. Will review with Matt and Graham to start formulating the discussion guide based on the prototype.

**Comment by KiahMadz** [comment]
8 participants scheduled. Consent forms sent and all have signed. Sending place holder meeting invites to the team today until an approach for observing sessions is confirmed. 

Discussion guide first draft written here: https://docs.google.com/document/d/145eBvXAIlQPjQXkRmU6Rba0NjocKe5r5-_nH_hno8hE/edit?usp=drive_link
