### ISSUE TITLE
Research synthesis and playback (prototype 1)

### ISSUE THREAD

**Issue by robertjmccarthy** [ministryofjustice/moj-frontend#951]
## What
Synthesise and analyse research sessions and playback insights to the team. Also, create a spreadsheet where insights can be stored, actioned, and tracked for implementation.

Where possible, play back an initial confidence level of the community space concept to the team as soon as possible.

## Why
Playing back an initial confidence level is key to providing the team the ability to be agile in decision making and shift our focus, intentions and direction depending on the confidence of the concept. Also, synthesising and analysing the detailed insights from the sessions needs to be done so that insights can be carried through into further iterations. This is also why it's important to include insights in a tracker so that we can be sure that the valuable insights are applied in future iterations of the work.

## Who needs to be involved
- User Researcher

## Done
When an initial confidence level is provided to the team, and when insights are played back to the team and added to a spreadsheet tracker.

**Comment by KiahMadz** [comment]
Summary report: https://docs.google.com/presentation/d/1FCtT3lAaLfJ6kpc5mRHNAb1qeV6O74_Ia5GJVR7F5uA/edit?usp=sharing

Playback in team away day tomorrow.
