### ISSUE TITLE
Prevent caching of guidance site HTML by browsers

### ISSUE THREAD

**Issue by chrispymm** [ministryofjustice/moj-frontend#965]
## What
As the guidance site is a static site, the HTML served by the server is cached by browsers.  This means a forced refresh is required by browsers after a deploy to pick up changes.

## Why
After deploying the site users will still see an old version until they hard refresh.

## Who needs to be involved
- Developer

## Done
Caching problem is solved

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the base.njk file to include version numbers in the CSS and JS file names. This will force browsers to download new versions after a deploy, solving the caching issue.

You can review changes in this commit: https://github.com/lkilu6456546/ministryofjustice-moj-frontend-965/commit/9627e0303e40669e9608f16212606a5db2f68d8b.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
