### ISSUE TITLE
Change Date picker component contributor section

### ISSUE THREAD

**Issue by robertjmccarthy** [ministryofjustice/moj-frontend#970]
## What
Change the contributor section of the Date picker component to reflect the contributors contributed the component as opposed to provided feedback. The section was correct previously, but it has since adopted a template. This work is likely to include untangling the templated approach taken for the contributor section.

## Why
The contributor section of the Date picker component is using a template (the same template that is in use on the Button menu component). The contributors contributed the component rather than provided feedback on it as part of a discovery.

## Who needs to be involved
- Interaction Designer
- Content Designer

## Done
When the Date picker component accurately reflects the contribution made and Dom Billington is notified the change had been made.

**Comment by murrlipp** [comment]
Awaiting PR check: https://github.com/ministryofjustice/moj-frontend/pull/976
